In [55]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [56]:
df = pd.read_csv(r"../data/raw/weatherHistory.csv")

In [57]:
print("Shape: ", df.shape)

Shape:  (96453, 12)

In [58]:
df.head()

,Formatted Date,Summary,Precip Type,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Loud Cover,Pressure (millibars),Daily Summary
0,2006-04-01 00:00:00.000 +0200,Partly Cloudy,rain,9.472222,7.388889,0.89,14.1197,251.0,15.8263,0.0,1015.13,Partly cloudy throughout the day.
1,2006-04-01 01:00:00.000 +0200,Partly Cloudy,rain,9.355556,7.227778,0.86,14.2646,259.0,15.8263,0.0,1015.63,Partly cloudy throughout the day.
2,2006-04-01 02:00:00.000 +0200,Mostly Cloudy,rain,9.377778,9.377778,0.89,3.9284,204.0,14.9569,0.0,1015.94,Partly cloudy throughout the day.
3,2006-04-01 03:00:00.000 +0200,Partly Cloudy,rain,8.288889,5.944444,0.83,14.1036,269.0,15.8263,0.0,1016.41,Partly cloudy throughout the day.
4,2006-04-01 04:00:00.000 +0200,Mostly Cloudy,rain,8.755556,6.977778,0.83,11.0446,259.0,15.8263,0.0,1016.51,Partly cloudy throughout the day.

In [59]:
print(df.columns.tolist())

['Formatted Date', 'Summary', 'Precip Type', 'Temperature (C)', 'Apparent Temperature (C)', 'Humidity', 'Wind Speed (km/h)', 'Wind Bearing (degrees)', 'Visibility (km)', 'Loud Cover', 'Pressure (millibars)', 'Daily Summary']

In [60]:
df = df.rename(columns={
    'Formatted Date': 'Date',
    'Summary': 'Summary',
    'Precip Type': 'Precip_Type',
    'Temperature (C)': 'Temperature',
    'Apparent Temperature (C)': 'Apparent_Temperature',
    'Humidity': 'Humidity',
    'Wind Speed (km/h)': 'Wind_Speed',
    'Wind Bearing (degrees)': 'Wind_Bearing',
    'Visibility (km)': 'Visibility',
    'Loud Cover': 'Cloud_Cover',
    'Pressure (millibars)': 'Pressure',
    'Daily Summary': 'Daily_Summary'
})
df.head()

,Date,Summary,Precip_Type,Temperature,Apparent_Temperature,Humidity,Wind_Speed,Wind_Bearing,Visibility,Cloud_Cover,Pressure,Daily_Summary
0,2006-04-01 00:00:00.000 +0200,Partly Cloudy,rain,9.472222,7.388889,0.89,14.1197,251.0,15.8263,0.0,1015.13,Partly cloudy throughout the day.
1,2006-04-01 01:00:00.000 +0200,Partly Cloudy,rain,9.355556,7.227778,0.86,14.2646,259.0,15.8263,0.0,1015.63,Partly cloudy throughout the day.
2,2006-04-01 02:00:00.000 +0200,Mostly Cloudy,rain,9.377778,9.377778,0.89,3.9284,204.0,14.9569,0.0,1015.94,Partly cloudy throughout the day.
3,2006-04-01 03:00:00.000 +0200,Partly Cloudy,rain,8.288889,5.944444,0.83,14.1036,269.0,15.8263,0.0,1016.41,Partly cloudy throughout the day.
4,2006-04-01 04:00:00.000 +0200,Mostly Cloudy,rain,8.755556,6.977778,0.83,11.0446,259.0,15.8263,0.0,1016.51,Partly cloudy throughout the day.

In [61]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 96453 entries, 0 to 96452
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Date                  96453 non-null  str
 1   Summary               96453 non-null  str
 2   Precip_Type           95936 non-null  str
 3   Temperature           96453 non-null  float64
 4   Apparent_Temperature  96453 non-null  float64
 5   Humidity              96453 non-null  float64
 6   Wind_Speed            96453 non-null  float64
 7   Wind_Bearing          96453 non-null  float64
 8   Visibility            96453 non-null  float64
 9   Cloud_Cover           96453 non-null  float64
 10  Pressure              96453 non-null  float64
 11  Daily_Summary         96453 non-null  str
dtypes: float64(8), str(4)
memory usage: 16.3 MB

In [62]:
df.isnull().sum()

Date                      0
Summary                   0
Precip_Type             517
Temperature               0
Apparent_Temperature      0
Humidity                  0
Wind_Speed                0
Wind_Bearing              0
Visibility                0
Cloud_Cover               0
Pressure                  0
Daily_Summary             0
dtype: int64

In [63]:
missing_percentage = (
    df.isnull().sum() / len(df) * 100
)
print(missing_percentage)

Date                    0.000000
Summary                 0.000000
Precip_Type             0.536012
Temperature             0.000000
Apparent_Temperature    0.000000
Humidity                0.000000
Wind_Speed              0.000000
Wind_Bearing            0.000000
Visibility              0.000000
Cloud_Cover             0.000000
Pressure                0.000000
Daily_Summary           0.000000
dtype: float64

In [64]:
print(df["Precip_Type"].value_counts(dropna=False))

Precip_Type
rain    85224
snow    10712
NaN       517
Name: count, dtype: int64

In [65]:
df["Precip_Type"] = df["Precip_Type"].fillna("none")

In [66]:
print(df["Precip_Type"].isnull().sum())

0

In [67]:
df.isnull().sum()

Date                    0
Summary                 0
Precip_Type             0
Temperature             0
Apparent_Temperature    0
Humidity                0
Wind_Speed              0
Wind_Bearing            0
Visibility              0
Cloud_Cover             0
Pressure                0
Daily_Summary           0
dtype: int64

In [68]:
duplicates = df.duplicated().sum()

print("Duplicate rows:", duplicates)

Duplicate rows: 24

In [69]:
df = df.drop_duplicates()

In [70]:
print("Shape after duplicate removal:", df.shape)

Shape after duplicate removal: (96429, 12)

In [71]:
df["Date"] = pd.to_datetime(
    df["Date"],
    utc=True
)
df.info()

<class 'pandas.DataFrame'>
Index: 96429 entries, 0 to 96452
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Date                  96429 non-null  datetime64[us, UTC]
 1   Summary               96429 non-null  str
 2   Precip_Type           96429 non-null  str
 3   Temperature           96429 non-null  float64
 4   Apparent_Temperature  96429 non-null  float64
 5   Humidity              96429 non-null  float64
 6   Wind_Speed            96429 non-null  float64
 7   Wind_Bearing          96429 non-null  float64
 8   Visibility            96429 non-null  float64
 9   Cloud_Cover           96429 non-null  float64
 10  Pressure              96429 non-null  float64
 11  Daily_Summary         96429 non-null  str
dtypes: datetime64[us, UTC](1), float64(8), str(3)
memory usage: 14.4 MB

In [72]:
print(df["Humidity"].describe())

count    96429.000000
mean         0.734902
std          0.195466
min          0.000000
25%          0.600000
50%          0.780000
75%          0.890000
max          1.000000
Name: Humidity, dtype: float64

In [73]:
print(df["Wind_Speed"].describe())

print(
    "Negative wind speeds:",
    (df["Wind_Speed"] < 0).sum()
)

count    96429.000000
mean        10.812460
std          6.913345
min          0.000000
25%          5.828200
50%          9.965900
75%         14.135800
max         63.852600
Name: Wind_Speed, dtype: float64
Negative wind speeds: 0

In [74]:
df["year"] = df["Date"].dt.year
df["month"] = df["Date"].dt.month
df["day"] = df["Date"].dt.day
df["hour"] = df["Date"].dt.hour
df["day_of_week"] = df["Date"].dt.dayofweek
df[[
    "Date",
    "year",
    "month",
    "day",
    "hour",
    "day_of_week"
]].head(10)

                       Date  year  month  day  hour  day_of_week
0 2006-03-31 22:00:00+00:00  2006      3   31    22            4
1 2006-03-31 23:00:00+00:00  2006      3   31    23            4
2 2006-04-01 00:00:00+00:00  2006      4    1     0            5
3 2006-04-01 01:00:00+00:00  2006      4    1     1            5
4 2006-04-01 02:00:00+00:00  2006      4    1     2            5
5 2006-04-01 03:00:00+00:00  2006      4    1     3            5
6 2006-04-01 04:00:00+00:00  2006      4    1     4            5
7 2006-04-01 05:00:00+00:00  2006      4    1     5            5
8 2006-04-01 06:00:00+00:00  2006      4    1     6            5
9 2006-04-01 07:00:00+00:00  2006      4    1     7            5

In [75]:
conditions = (
    (df["Wind_Speed"] < 20) &
    (df["Humidity"] < 0.80) &
    (df["Temperature"] > 18) &
    (df["Apparent_Temperature"] < 32) &
    (~df["Precip_Type"].isin(["rain", "snow"]))
)

df["suitability"] = np.where(
    conditions,
    "Suitable",
    "Not Suitable"
)
print(df["suitability"].value_counts())

suitability
Not Suitable    96406
Suitable           23
Name: count, dtype: int64

In [76]:
df['Summary'].value_counts()

Summary
Partly Cloudy                          31726
Mostly Cloudy                          28094
Overcast                               16597
Clear                                  10873
Foggy                                   7148
Breezy and Overcast                      528
Breezy and Mostly Cloudy                 516
Breezy and Partly Cloudy                 386
Dry and Partly Cloudy                     86
Windy and Partly Cloudy                   67
Light Rain                                63
Breezy                                    54
Windy and Overcast                        45
Humid and Mostly Cloudy                   40
Drizzle                                   39
Breezy and Foggy                          35
Windy and Mostly Cloudy                   35
Dry                                       34
Humid and Partly Cloudy                   17
Dry and Mostly Cloudy                     14
Rain                                      10
Windy                                      8
Humid and Overcast                         7
Windy and Foggy                            4
Dangerously Windy and Partly Cloudy        1
Windy and Dry                              1
Breezy and Dry                             1
Name: count, dtype: int64

In [78]:
def simplify_weather(summary):
    summary = summary.lower()

    if 'rain' in summary or 'drizzle' in summary:
        return 'Rainy'
    elif 'foggy' in summary:
        return 'Foggy'
    elif 'cloudy' in summary or 'overcast' in summary:
        return 'Cloudy'
    elif 'clear' in summary:
        return 'Clear'
    elif 'windy' in summary or 'breezy' in summary:
        return 'Windy'
    else:
        return 'Other'

df['Daily_Summary'] = df['Daily_Summary'].apply(simplify_weather)

In [79]:
df.to_csv("../data/processed/weatherHistory_cleaned.csv", index=False)